package com.codelegends.logistics.dto;

import com.codelegends.logistics.entity.*;
import com.fasterxml.jackson.annotation.JsonProperty;

import jakarta.validation.constraints.*;

import lombok.*;

import java.time.*;
import java.util.List;

/**
 * Transfers address data between API clients and the service layer.
 */
// Generates standard accessors so the DTO remains a simple transport object.
@Data
// Enables readable construction when services map entities into this DTO.
@Builder
// Provides the empty constructor required by JSON binding frameworks.
@NoArgsConstructor
// Provides a full-value constructor for tests and controlled DTO creation.
@AllArgsConstructor
public class AddressDTO {
    // Exposes the generated identifier in responses while preventing client-side assignment.
    @JsonProperty(access = JsonProperty.Access.READ_ONLY)
    /** API-visible identifier generated by persistence. */
    private Long id;

    @NotBlank
    @Size(max = 200)
    /** Stores the street address line used for customer location records. */
    private String street;

    @NotBlank
    @Size(max = 100)
    /** Stores the city portion of the address. */
    private String city;

    @NotBlank
    @Size(max = 20)
    /** Stores the postal code portion of the address. */
    private String postalCode;

    @NotBlank
    @Size(max = 100)
    /** Stores the country associated with the resource. */
    private String country;

    /** References the customer that owns this address. */
    @NotNull @Positive private Long customerId;

    /** References the service zone that covers this address. */
    @NotNull @Positive private Long serviceZoneId;

    /** Maps a persisted entity into its API response representation. */
    public static AddressDTO convertToDTO(Address entity) {
        return AddressDTO.builder()
                .id(entity.getId())
                .street(entity.getStreet())
                .city(entity.getCity())
                .postalCode(entity.getPostalCode())
                .country(entity.getCountry())
                .customerId(entity.getCustomer().getId())
                .serviceZoneId(entity.getServiceZone().getId())
                .build();
    }

    /** Converts a collection of entities into DTOs for list responses. */
    public static List<AddressDTO> convertToDTO(List<Address> entities) {
        return entities.stream().map(AddressDTO::convertToDTO).toList();
    }
}
