package com.codelegends.logistics.dto;

import com.codelegends.logistics.entity.*;
import com.fasterxml.jackson.annotation.JsonProperty;

import jakarta.validation.constraints.*;

import lombok.*;

import java.time.*;
import java.util.List;

/**
 * Transfers carrier data between API clients and the service layer.
 */
// Generates standard accessors so the DTO remains a simple transport object.
@Data
// Enables readable construction when services map entities into this DTO.
@Builder
// Provides the empty constructor required by JSON binding frameworks.
@NoArgsConstructor
// Provides a full-value constructor for tests and controlled DTO creation.
@AllArgsConstructor
public class CarrierDTO {
    // Exposes the generated identifier in responses while preventing client-side assignment.
    @JsonProperty(access = JsonProperty.Access.READ_ONLY)
    /** API-visible identifier generated by persistence. */
    private Long id;

    @NotBlank
    // Requires a valid the name value for API request processing.
    @Size(max = 100)
    /** Stores the display name for the resource. */
    private String name;

    @NotBlank
    @Size(max = 150)
    // Requires the contact email so invalid DTO payloads are rejected early.
    @Email
    // Accepts contact email values for write requests without returning them in API responses.
    // Accepts phone values for write requests while preventing response serialization.
    @JsonProperty(access = JsonProperty.Access.WRITE_ONLY)
    /** Accepts the carrier contact email during write operations. */
    private String contactEmail;

    @NotBlank
    // Validates the phone number before the value is passed to service logic.
    @Size(max = 20)
    @JsonProperty(access = JsonProperty.Access.WRITE_ONLY)
    /** Accepts the phone number during write operations while keeping it out of responses. */
    private String phoneNumber;

    @NotBlank
    // Keeps the country constrained to the accepted request shape.
    @Size(max = 100)
    /** Stores the country associated with the resource. */
    private String country;

    /** Maps a persisted entity into its API response representation. */
    public static CarrierDTO convertToDTO(Carrier entity) {
        return CarrierDTO.builder()
                .id(entity.getId())
                .name(entity.getName())
                .country(entity.getCountry())
                .build();
    }

    /** Converts a collection of entities into DTOs for list responses. */
    public static List<CarrierDTO> convertToDTO(List<Carrier> entities) {
        return entities.stream().map(CarrierDTO::convertToDTO).toList();
    }
}
