package com.codelegends.logistics.dto;

import com.codelegends.logistics.entity.*;
import com.fasterxml.jackson.annotation.JsonProperty;

import jakarta.validation.constraints.*;

import lombok.*;

import java.time.*;
import java.util.List;

/**
 * Transfers customer data between API clients and the service layer.
 */
// Generates standard accessors so the DTO remains a simple transport object.
@Data
// Enables readable construction when services map entities into this DTO.
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class CustomerDTO {
    @JsonProperty(access = JsonProperty.Access.READ_ONLY)
    /** API-visible identifier generated by persistence. */
    private Long id;

    @NotBlank
    @Size(max = 100)
    /** Stores the display name for the resource. */
    private String name;

    @NotBlank
    @Size(max = 150)
    @Email
    @JsonProperty(access = JsonProperty.Access.WRITE_ONLY)
    /** Accepts the customer email during write operations. */
    private String email;

    @NotBlank
    @Size(max = 20)
    @JsonProperty(access = JsonProperty.Access.WRITE_ONLY)
    /** Accepts the phone number during write operations while keeping it out of responses. */
    private String phoneNumber;

    /** Classifies the customer as an individual or business account. */
    @NotNull private CustomerType type;

    /** Maps a persisted entity into its API response representation. */
    public static CustomerDTO convertToDTO(Customer entity) {
        return CustomerDTO.builder()
                .id(entity.getId())
                .name(entity.getName())
                .type(entity.getType())
                .build();
    }

    /** Converts a collection of entities into DTOs for list responses. */
    public static List<CustomerDTO> convertToDTO(List<Customer> entities) {
        return entities.stream().map(CustomerDTO::convertToDTO).toList();
    }
}
