package com.codelegends.logistics.dto;

import com.codelegends.logistics.entity.*;
import com.fasterxml.jackson.annotation.JsonProperty;

import jakarta.validation.constraints.*;

import lombok.*;

import java.time.*;
import java.util.List;

/**
 * Transfers deliverystop data between API clients and the service layer.
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class DeliveryStopDTO {
    @JsonProperty(access = JsonProperty.Access.READ_ONLY)
    /** API-visible identifier generated by persistence. */
    private Long id;

    @NotNull @Positive private Integer sequence;

    @NotBlank
    @Size(max = 300)
    /** Stores the delivery address for the stop. */
    private String address;

    @NotNull private StopStatus status;

    @NotNull private LocalDateTime eta;

    @NotNull @Positive private Long routeId;

    @NotNull @Positive private Long shipmentId;

    /** Maps a persisted entity into its API response representation. */
    public static DeliveryStopDTO convertToDTO(DeliveryStop entity) {
        return DeliveryStopDTO.builder()
                .id(entity.getId())
                .sequence(entity.getSequence())
                .address(entity.getAddress())
                .status(entity.getStatus())
                .eta(entity.getEta())
                .routeId(entity.getRoute().getId())
                .shipmentId(entity.getShipment().getId())
                .build();
    }

    /** Converts a collection of entities into DTOs for list responses. */
    public static List<DeliveryStopDTO> convertToDTO(List<DeliveryStop> entities) {
        return entities.stream().map(DeliveryStopDTO::convertToDTO).toList();
    }
}
