package com.codelegends.logistics.dto;

import com.codelegends.logistics.entity.*;
import com.fasterxml.jackson.annotation.JsonProperty;

import jakarta.validation.constraints.*;

import lombok.*;

import java.time.*;
import java.util.List;

/**
 * Transfers driver data between API clients and the service layer.
 */
// Generates standard accessors so the DTO remains a simple transport object.
@Data
// Enables readable construction when services map entities into this DTO.
@Builder
// Provides the empty constructor required by JSON binding frameworks.
@NoArgsConstructor
// Provides a full-value constructor for tests and controlled DTO creation.
@AllArgsConstructor
public class DriverDTO {
    // Exposes the generated identifier in responses while preventing client-side assignment.
    @JsonProperty(access = JsonProperty.Access.READ_ONLY)
    /** API-visible identifier generated by persistence. */
    private Long id;

    @NotBlank
    // Requires a valid the name value for API request processing.
    @Size(max = 100)
    /** Stores the display name for the resource. */
    private String name;

    @NotBlank
    // Requires the license number so invalid DTO payloads are rejected early.
    @Size(max = 50)
    // Accepts license values during driver writes without exposing them through reads.
    // Accepts phone values for write requests while preventing response serialization.
    @JsonProperty(access = JsonProperty.Access.WRITE_ONLY)
    /** Accepts the driver license number during write operations. */
    private String licenseNumber;

    @NotBlank
    // Validates the phone number before the value is passed to service logic.
    @Size(max = 20)
    @JsonProperty(access = JsonProperty.Access.WRITE_ONLY)
    /** Accepts the phone number during write operations while keeping it out of responses. */
    private String phoneNumber;

    /** Tracks whether the driver is available, assigned, or unavailable for maintenance. */
    // Keeps the status constrained to the accepted request shape.
    @NotNull private Availability status;

    /** References the carrier that employs the driver. */
    // Ensures the carrier identifier is present and meaningful for this DTO.
    @NotNull @Positive private Long carrierId;

    /** Maps a persisted entity into its API response representation. */
    public static DriverDTO convertToDTO(Driver entity) {
        return DriverDTO.builder()
                .id(entity.getId())
                .name(entity.getName())
                .status(entity.getStatus())
                .carrierId(entity.getCarrier().getId())
                .build();
    }

    /** Converts a collection of entities into DTOs for list responses. */
    public static List<DriverDTO> convertToDTO(List<Driver> entities) {
        return entities.stream().map(DriverDTO::convertToDTO).toList();
    }
}
