package com.codelegends.logistics.dto;

import com.codelegends.logistics.entity.*;
import com.fasterxml.jackson.annotation.JsonProperty;

import jakarta.validation.constraints.*;

import lombok.*;

import java.time.*;
import java.util.List;

/**
 * Transfers inventoryitem data between API clients and the service layer.
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class InventoryItemDTO {
    @JsonProperty(access = JsonProperty.Access.READ_ONLY)
    /** API-visible identifier generated by persistence. */
    private Long id;

    @NotNull @PositiveOrZero private Integer quantity;

    @NotBlank
    @Size(max = 100)
    /** Stores the warehouse shelf location for inventory placement. */
    private String shelfLocation;

    @NotNull @Positive private Long warehouseId;

    @NotNull @Positive private Long productId;

    /** Maps a persisted entity into its API response representation. */
    public static InventoryItemDTO convertToDTO(InventoryItem entity) {
        return InventoryItemDTO.builder()
                .id(entity.getId())
                .quantity(entity.getQuantity())
                .shelfLocation(entity.getShelfLocation())
                .warehouseId(entity.getWarehouse().getId())
                .productId(entity.getProduct().getId())
                .build();
    }

    /** Converts a collection of entities into DTOs for list responses. */
    public static List<InventoryItemDTO> convertToDTO(List<InventoryItem> entities) {
        return entities.stream().map(InventoryItemDTO::convertToDTO).toList();
    }
}
