package com.codelegends.logistics.dto;

import com.codelegends.logistics.entity.*;
import com.fasterxml.jackson.annotation.JsonProperty;

import jakarta.validation.constraints.*;

import lombok.*;

import java.math.BigDecimal;
import java.time.*;
import java.util.List;

/**
 * Transfers invoice data between API clients and the service layer.
 */
// Generates standard accessors so the DTO remains a simple transport object.
@Data
// Enables readable construction when services map entities into this DTO.
@Builder
// Provides the empty constructor required by JSON binding frameworks.
@NoArgsConstructor
// Provides a full-value constructor for tests and controlled DTO creation.
@AllArgsConstructor
public class InvoiceDTO {
    @JsonProperty(access = JsonProperty.Access.READ_ONLY)
    /** API-visible identifier generated by persistence. */
    private Long id;

    @NotNull
    @DecimalMin("0.01")
    @Digits(integer = 10, fraction = 2)
    /** Stores the invoice amount with currency-scale precision. */
    private BigDecimal amount;

    /** Tracks whether payment is still outstanding. */
    @NotNull private InvoiceStatus status;

    /** Records when the invoice was issued. */
    @NotNull @PastOrPresent private LocalDateTime issuedDate;

    /** References the delivered shipment being billed. */
    @NotNull @Positive private Long shipmentId;

    /** References the customer responsible for the invoice. */
    @NotNull @Positive private Long customerId;

    /** Maps a persisted entity into its API response representation. */
    public static InvoiceDTO convertToDTO(Invoice entity) {
        return InvoiceDTO.builder()
                .id(entity.getId())
                .amount(entity.getAmount())
                .status(entity.getStatus())
                .issuedDate(entity.getIssuedDate())
                .shipmentId(entity.getShipment().getId())
                .customerId(entity.getCustomer().getId())
                .build();
    }

    /** Converts a collection of entities into DTOs for list responses. */
    public static List<InvoiceDTO> convertToDTO(List<Invoice> entities) {
        return entities.stream().map(InvoiceDTO::convertToDTO).toList();
    }
}
