package com.codelegends.logistics.dto;

import com.codelegends.logistics.entity.*;
import com.fasterxml.jackson.annotation.JsonProperty;

import jakarta.validation.constraints.*;

import lombok.*;

import java.math.BigDecimal;
import java.time.*;
import java.util.List;

/**
 * Transfers product data between API clients and the service layer.
 */
// Generates standard accessors so the DTO remains a simple transport object.
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class ProductDTO {
    @JsonProperty(access = JsonProperty.Access.READ_ONLY)
    /** API-visible identifier generated by persistence. */
    private Long id;

    @NotBlank
    @Size(max = 120)
    /** Stores the display name for the resource. */
    private String name;

    @NotBlank
    @Size(max = 50)
    /** Stores the unique product stock keeping unit. */
    private String sku;

    @NotNull
    @DecimalMin("0.01")
    @Digits(integer = 10, fraction = 2)
    /** Stores product weight in kilograms for shipment weight calculations. */
    private BigDecimal weightKg;

    @NotBlank
    @Size(max = 100)
    /** Stores the product category used for catalog grouping. */
    private String category;

    /** Maps a persisted entity into its API response representation. */
    public static ProductDTO convertToDTO(Product entity) {
        return ProductDTO.builder()
                .id(entity.getId())
                .name(entity.getName())
                .sku(entity.getSku())
                .weightKg(entity.getWeightKg())
                .category(entity.getCategory())
                .build();
    }

    /** Converts a collection of entities into DTOs for list responses. */
    public static List<ProductDTO> convertToDTO(List<Product> entities) {
        return entities.stream().map(ProductDTO::convertToDTO).toList();
    }
}
