package com.codelegends.logistics.dto;

import com.codelegends.logistics.entity.*;
import com.fasterxml.jackson.annotation.JsonProperty;

import jakarta.validation.constraints.*;

import lombok.*;

import java.time.*;
import java.util.List;

/**
 * Transfers route data between API clients and the service layer.
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class RouteDTO {
    @JsonProperty(access = JsonProperty.Access.READ_ONLY)
    /** API-visible identifier generated by persistence. */
    private Long id;

    @NotNull private LocalDate routeDate;

    @NotBlank
    @Size(max = 200)
    /** Stores the route starting location. */
    private String origin;

    @NotBlank
    @Size(max = 200)
    /** Stores the route destination. */
    private String destination;

    @NotNull private RouteStatus status;

    @NotNull @Positive private Long vehicleId;

    @NotNull @Positive private Long driverId;

    /** Maps a persisted entity into its API response representation. */
    public static RouteDTO convertToDTO(Route entity) {
        return RouteDTO.builder()
                .id(entity.getId())
                .routeDate(entity.getRouteDate())
                .origin(entity.getOrigin())
                .destination(entity.getDestination())
                .status(entity.getStatus())
                .vehicleId(entity.getVehicle().getId())
                .driverId(entity.getDriver().getId())
                .build();
    }

    /** Converts a collection of entities into DTOs for list responses. */
    public static List<RouteDTO> convertToDTO(List<Route> entities) {
        return entities.stream().map(RouteDTO::convertToDTO).toList();
    }
}
