package com.codelegends.logistics.dto;

import com.codelegends.logistics.entity.*;
import com.fasterxml.jackson.annotation.JsonProperty;

import jakarta.validation.constraints.*;

import lombok.*;

import java.math.BigDecimal;
import java.time.*;
import java.util.List;

/**
 * Transfers service zone data between API clients and the service layer.
 */
// Generates standard accessors so the DTO remains a simple transport object.
@Data
// Enables readable construction when services map entities into this DTO.
@Builder
// Provides the empty constructor required by JSON binding frameworks.
@NoArgsConstructor
@AllArgsConstructor
public class ServiceZoneDTO {
    @JsonProperty(access = JsonProperty.Access.READ_ONLY)
    /** API-visible identifier generated by persistence. */
    private Long id;

    @NotBlank
    @Size(max = 100)
    /** Stores the display name for the resource. */
    private String name;

    @NotBlank
    @Size(max = 100)
    /** Stores the service region covered by the zone. */
    private String region;

    @NotNull
    @DecimalMin("0.01")
    @Digits(integer = 10, fraction = 2)
    /** Stores the base service rate for the zone. */
    private BigDecimal baseRate;

    /** Maps a persisted entity into its API response representation. */
    public static ServiceZoneDTO convertToDTO(ServiceZone entity) {
        return ServiceZoneDTO.builder()
                .id(entity.getId())
                .name(entity.getName())
                .region(entity.getRegion())
                .baseRate(entity.getBaseRate())
                .build();
    }

    /** Converts a collection of entities into DTOs for list responses. */
    public static List<ServiceZoneDTO> convertToDTO(List<ServiceZone> entities) {
        return entities.stream().map(ServiceZoneDTO::convertToDTO).toList();
    }
}
