package com.codelegends.logistics.dto;

import com.codelegends.logistics.entity.*;
import com.fasterxml.jackson.annotation.JsonProperty;

import jakarta.validation.constraints.*;

import lombok.*;

import java.math.BigDecimal;
import java.time.*;
import java.util.List;

/**
 * Transfers shipment data between API clients and the service layer.
 */
// Generates standard accessors so the DTO remains a simple transport object.
@Data
// Enables readable construction when services map entities into this DTO.
@Builder
// Provides the empty constructor required by JSON binding frameworks.
@NoArgsConstructor
// Provides a full-value constructor for tests and controlled DTO creation.
@AllArgsConstructor
public class ShipmentDTO {
    @JsonProperty(access = JsonProperty.Access.READ_ONLY)
    /** API-visible identifier generated by persistence. */
    private Long id;

    /** Records when the shipment was created or registered. */
    @NotNull @PastOrPresent private LocalDateTime shipmentDate;

    /** Tracks the current shipment lifecycle state. */
    @NotNull private ShipmentStatus status;

    @NotNull
    @PositiveOrZero
    @Digits(integer = 10, fraction = 2)
    /** Stores the shipment weight derived from active shipment items. */
    private BigDecimal totalWeight;

    /** References the warehouse dispatching the shipment. */
    @NotNull @Positive private Long warehouseId;

    /** References the customer that owns the shipment. */
    @NotNull @Positive private Long customerId;

    /** References the carrier assigned to transport the shipment. */
    @NotNull @Positive private Long carrierId;

    /** Maps a persisted entity into its API response representation. */
    public static ShipmentDTO convertToDTO(Shipment entity) {
        return ShipmentDTO.builder()
                .id(entity.getId())
                .shipmentDate(entity.getShipmentDate())
                .status(entity.getStatus())
                .totalWeight(entity.getTotalWeight())
                .warehouseId(entity.getWarehouse().getId())
                .customerId(entity.getCustomer().getId())
                .carrierId(entity.getCarrier().getId())
                .build();
    }

    /** Converts a collection of entities into DTOs for list responses. */
    public static List<ShipmentDTO> convertToDTO(List<Shipment> entities) {
        return entities.stream().map(ShipmentDTO::convertToDTO).toList();
    }
}
