package com.codelegends.logistics.dto;

import com.codelegends.logistics.entity.*;
import com.fasterxml.jackson.annotation.JsonProperty;

import jakarta.validation.constraints.*;

import lombok.*;

import java.time.*;
import java.util.List;

/**
 * Transfers staff data between API clients and the service layer.
 */
// Generates standard accessors so the DTO remains a simple transport object.
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class StaffDTO {
    @JsonProperty(access = JsonProperty.Access.READ_ONLY)
    /** API-visible identifier generated by persistence. */
    private Long id;

    @NotBlank
    @Size(max = 100)
    /** Stores the display name for the resource. */
    private String name;

    @NotBlank
    @Size(max = 100)
    /** Stores the staff role within the warehouse. */
    private String role;

    @NotBlank
    @Size(max = 20)
    @JsonProperty(access = JsonProperty.Access.WRITE_ONLY)
    /** Accepts the phone number during write operations while keeping it out of responses. */
    private String phoneNumber;

    /** References the warehouse where the staff member works. */
    @NotNull @Positive private Long warehouseId;

    /** Maps a persisted entity into its API response representation. */
    public static StaffDTO convertToDTO(Staff entity) {
        return StaffDTO.builder()
                .id(entity.getId())
                .name(entity.getName())
                .role(entity.getRole())
                .warehouseId(entity.getWarehouse().getId())
                .build();
    }

    /** Converts a collection of entities into DTOs for list responses. */
    public static List<StaffDTO> convertToDTO(List<Staff> entities) {
        return entities.stream().map(StaffDTO::convertToDTO).toList();
    }
}
