package com.codelegends.logistics.dto;

import com.codelegends.logistics.entity.*;
import com.fasterxml.jackson.annotation.JsonProperty;

import jakarta.validation.constraints.*;

import lombok.*;

import java.time.*;
import java.util.List;

/**
 * Transfers trackingevent data between API clients and the service layer.
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class TrackingEventDTO {
    @JsonProperty(access = JsonProperty.Access.READ_ONLY)
    /** API-visible identifier generated by persistence. */
    private Long id;

    @NotNull @PastOrPresent private LocalDateTime eventTime;

    @NotBlank
    @Size(max = 200)
    /** Stores where the tracking event was recorded. */
    private String location;

    @NotNull private ShipmentStatus status;

    @NotBlank
    @Size(max = 500)
    /** Stores the human-readable tracking event note. */
    private String note;

    @NotNull @Positive private Long shipmentId;

    /** Maps a persisted entity into its API response representation. */
    public static TrackingEventDTO convertToDTO(TrackingEvent entity) {
        return TrackingEventDTO.builder()
                .id(entity.getId())
                .eventTime(entity.getEventTime())
                .location(entity.getLocation())
                .status(entity.getStatus())
                .note(entity.getNote())
                .shipmentId(entity.getShipment().getId())
                .build();
    }

    /** Converts a collection of entities into DTOs for list responses. */
    public static List<TrackingEventDTO> convertToDTO(List<TrackingEvent> entities) {
        return entities.stream().map(TrackingEventDTO::convertToDTO).toList();
    }
}
