package com.codelegends.logistics.dto;

import com.codelegends.logistics.entity.*;
import com.fasterxml.jackson.annotation.JsonProperty;

import jakarta.validation.constraints.*;

import lombok.*;

import java.math.BigDecimal;
import java.time.*;
import java.util.List;

/**
 * Transfers vehicle data between API clients and the service layer.
 */
// Generates standard accessors so the DTO remains a simple transport object.
@Data
// Enables readable construction when services map entities into this DTO.
@Builder
// Provides the empty constructor required by JSON binding frameworks.
@NoArgsConstructor
// Provides a full-value constructor for tests and controlled DTO creation.
@AllArgsConstructor
public class VehicleDTO {
    // Exposes the generated identifier in responses while preventing client-side assignment.
    @JsonProperty(access = JsonProperty.Access.READ_ONLY)
    /** API-visible identifier generated by persistence. */
    private Long id;

    @NotBlank
    @Size(max = 30)
    /** Stores the vehicle plate number. */
    private String plateNumber;

    /** Identifies the vehicle category used for fleet planning. */
    @NotNull private VehicleType type;

    @NotNull
    @DecimalMin("0.01")
    @Digits(integer = 10, fraction = 2)
    /** Stores vehicle capacity in kilograms. */
    private BigDecimal capacityKg;

    /** Tracks whether the vehicle is available, assigned, or in maintenance. */
    @NotNull private Availability status;

    /** References the carrier that owns the vehicle. */
    @NotNull @Positive private Long carrierId;

    /** Maps a persisted entity into its API response representation. */
    public static VehicleDTO convertToDTO(Vehicle entity) {
        return VehicleDTO.builder()
                .id(entity.getId())
                .plateNumber(entity.getPlateNumber())
                .type(entity.getType())
                .capacityKg(entity.getCapacityKg())
                .status(entity.getStatus())
                .carrierId(entity.getCarrier().getId())
                .build();
    }

    /** Converts a collection of entities into DTOs for list responses. */
    public static List<VehicleDTO> convertToDTO(List<Vehicle> entities) {
        return entities.stream().map(VehicleDTO::convertToDTO).toList();
    }
}
