package com.codelegends.logistics.dto;

import com.codelegends.logistics.entity.*;
import com.fasterxml.jackson.annotation.JsonProperty;

import jakarta.validation.constraints.*;

import lombok.*;

import java.time.*;
import java.util.List;

/**
 * Transfers warehouse data between API clients and the service layer.
 */
// Generates standard accessors so the DTO remains a simple transport object.
@Data
// Enables readable construction when services map entities into this DTO.
@Builder
// Provides the empty constructor required by JSON binding frameworks.
@NoArgsConstructor
// Provides a full-value constructor for tests and controlled DTO creation.
@AllArgsConstructor
public class WarehouseDTO {
    @JsonProperty(access = JsonProperty.Access.READ_ONLY)
    /** API-visible identifier generated by persistence. */
    private Long id;

    @NotBlank
    @Size(max = 100)
    /** Stores the display name for the resource. */
    private String name;

    @NotBlank
    @Size(max = 200)
    /** Stores where the tracking event was recorded. */
    private String location;

    /** Defines the warehouse inventory capacity used by stock validation. */
    @NotNull @Positive private Integer capacity;

    /** Maps a persisted entity into its API response representation. */
    public static WarehouseDTO convertToDTO(Warehouse entity) {
        return WarehouseDTO.builder()
                .id(entity.getId())
                .name(entity.getName())
                .location(entity.getLocation())
                .capacity(entity.getCapacity())
                .build();
    }

    /** Converts a collection of entities into DTOs for list responses. */
    public static List<WarehouseDTO> convertToDTO(List<Warehouse> entities) {
        return entities.stream().map(WarehouseDTO::convertToDTO).toList();
    }
}
