package com.codelegends.logistics.entity;

import jakarta.persistence.*;

import lombok.Getter;
import lombok.Setter;

import java.time.LocalDateTime;

@MappedSuperclass
@Getter
@Setter
public abstract class BaseClass {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    /** API-visible identifier generated by persistence. */
    private Long id;

    @Column(nullable = false)
    /** Marks whether the row is visible to active-resource queries. */
    private boolean isActive = true;

    @Column(nullable = false, updatable = false)
    /** Captures when the entity was first persisted. */
    private LocalDateTime createdDate;

    @Column(nullable = false)
    /** Captures the most recent persistence update time. */
    private LocalDateTime updatedDate;

    @Version private Long version;

    /** Initializes audit timestamps before the first insert. */
    @PrePersist
    /** Captures when the entity was first persisted. */
    protected void beforeCreate() {
        createdDate = LocalDateTime.now();
        updatedDate = createdDate;
    }

    /** Refreshes the update timestamp before persistence changes are written. */
    @PreUpdate
    /** Captures the most recent persistence update time. */
    protected void beforeUpdate() {
        updatedDate = LocalDateTime.now();
    }
}
